default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USER_DEV"] %>
  password: <%= ENV["DATABASE_PASSWORD_DEV"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: racha_development

test:
  <<: *default
  database: racha_test

production:
  <<: *default
  database: racha_production
  username: <%= ENV["DATABASE_USER_PROD"] %>
  password: <%= ENV["DATABASE_PASSWORD_PROD"] %>
